const typography = {
  fontFamily: 'Montserrat',
  htmlFontSize: 10,
  h1: {
    fontSize: '3.2rem !important',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1,
    letterSpacing: 'normal',
  },
  h2: {
    fontSize: '2.4rem !important',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1,
    letterSpacing: 'normal',
  },
  h3: {
    fontSize: '2.0rem !important',
    fontWeight: 800,
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1.2,
    letterSpacing: 'normal',
  },
  h4: {
    fontSize: '2.0rem !important',
    fontWeight: 500,
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1,
    letterSpacing: 'normal',
  },
  h5: {
    fontSize: '1.8rem !important',
    fontWeight: 500,
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1,
    letterSpacing: 'normal',
  },
  h6: {
    fontSize: '1.6rem !important',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1,
    letterSpacing: 'normal',
  },
  subtitle1: {
    fontSize: '1.2rem !important',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1.17,
    letterSpacing: '0.12rem',
  },
  subtitle2: {
    fontSize: '1.3rem !important',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1.08,
    letterSpacing: 'normal',
  },
  body1: {
    fontSize: '1.6rem !important',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1.19,
    letterSpacing: 'normal',
  },
  body2: {
    fontSize: '1.4rem !important',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1.21,
    letterSpacing: 'normal',
  },
  button: {
    fontSize: '1.3rem !important',
    fontWeight: 600,
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1.08,
    letterSpacing: 'normal',
  },
  caption: {
    fontSize: '1.2rem !important',
    fontWeight: 'normal',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1.17,
    letterSpacing: 'normal',
  },
  overline: {
    fontSize: '1rem !important',
    fontWeight: 'bold',
    fontStretch: 'normal',
    fontStyle: 'normal',
    lineHeight: 1.2,
    letterSpacing: '0.1rem',
  },
};

export default typography;
